#define PRO_USE_VAR_ARGS true

#include "PTApplsUnicodeUtils.cpp"
#include "TestCollect.cpp"
#include "TestError.cpp"
#include "TestQcr.cpp"
#include "TestRunmode.cpp"
#include "UtilArcEndPoints.cpp"
#include "UtilCable.cpp"
#include "UtilCollect.cpp"
#include "UtilCollectDtmpnt.cpp"
#include "UtilError.cpp"
#include "UtilFiles.cpp"
#include "UtilGroups.cpp"
#include "UtilIntfData.cpp"
#include "UtilMath.cpp"
#include "UtilMatrix.cpp"
#include "UtilMenu.cpp"
#include "UtilMessage.cpp"
#include "UtilNames.cpp"
#include "UtilString.cpp"
#include "UtilTree.cpp"
#include "UtilTypes.cpp"
#include "UtilVisit.cpp"
